# Generated by Django 4.2.9 on 2025-01-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="calendar_public",
            field=models.BooleanField(
                default=False,
                help_text="If checked, other users can see your events. If unchecked, your events are private.",
                verbose_name="Make calendar public",
            ),
        ),
    ]
