# Generated by Django 4.2.9 on 2025-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_calendar_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calendar_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="event_preferences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
