# Generated by Django 4.2.9 on 2025-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_calendar_email_profile_event_preferences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="calendar_email",
        ),
        migrations.AddField(
            model_name="profile",
            name="google_calendar_connected",
            field=models.BooleanField(default=False),
        ),
    ]
