# Generated by Django 4.2.9 on 2025-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_remove_profile_calendar_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_google_calendar_access",
            field=models.BooleanField(default=False),
        ),
    ]
