# Generated by Django 4.2.9 on 2025-01-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_end_time_alter_event_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="spotify_artist_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="spotify_external_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="spotify_preview_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="spotify_track_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="spotify_track_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
