# Generated by Django 4.2.9 on 2025-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0005_event_spotify_artist_name_event_spotify_external_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="spotify_artist_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
