# Generated by Django 4.2.9 on 2025-01-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0005_event_spotify_artist_name_event_spotify_external_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="spotify_artist_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_artist_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_external_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_preview_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_track_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_track_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
