# Generated by Django 4.2.9 on 2025-01-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_spotify_artist_id_and_more"),
    ]

    operations = []
