# Generated by Django 4.2.9 on 2025-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_merge_20250127_0043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="spotify_artist_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_artist_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_external_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_preview_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_track_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="spotify_track_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
