# Generated by Django 4.2.9 on 2025-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_spotify_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='spotify_artist_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='spotify_artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='spotify_track_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
