# Generated by Django 4.2.9 on 2025-02-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_label"),
        ("events", "0010_starredevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="profiles.label"
            ),
        ),
    ]
