services:
  - type: web
    name: socialcal
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn socialcal.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: socialcal.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: socialcal_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      # Email configuration
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      # API Keys
      - key: SIMPLESCRAPER_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OLOSTEP_API_KEY
        sync: false

  - name: socialcal_db
    plan: free
    databaseName: socialcal
    ipAllowList: [] # only allow internal connections 