services:
  - type: web
    name: socialcal
    runtime: docker
    plan: standard
    healthCheckPath: /admin/login/
    buildCommand: DOCKER_BUILDKIT=1 docker build -t socialcal .
    startCommand: docker run -p $PORT:$PORT socialcal
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numInstances: 1
    envVars:
      - key: PORT
        value: 8000
      - key: DJANGO_SETTINGS_MODULE
        value: socialcal.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: socialcal_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      # Email configuration
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      # API Keys
      - key: SIMPLESCRAPER_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OLOSTEP_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          name: socialcal-redis
          type: redis
          property: connectionString
    disk:
      name: socialcal-data
      mountPath: /app/data
      sizeGB: 1

  - type: redis
    name: socialcal-redis
    ipAllowList: []
    plan: free

databases:
  - name: socialcal_db
    ipAllowList: []