services:
  - type: web
    name: socialcal
    env: docker
    buildCommand: DOCKER_BUILDKIT=1 docker build -t socialcal .
    startCommand: docker run -p $PORT:8000 socialcal
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socialcal-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: socialcal-redis
          type: redis
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "socialcal.settings.production"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OLOSTEP_API_KEY
        sync: false
    disk:
      name: socialcal-data
      mountPath: /app/data
      sizeGB: 1

  - type: redis
    name: socialcal-redis
    ipAllowList: []
    plan: free

databases:
  - name: socialcal-db
    databaseName: socialcal
    user: socialcal
    ipAllowList: []